### ISSUE TITLE
[FIX]Batch job submission failed: Requested time limit is invalid (missing or exceeds some limit)

### ISSUE THREAD

**Issue by yibeichan** [PennLINC/babs#118]
(I'm testing the example walkthrough on SLURM using Princeton cluster) In the walkthrough [Step 2.2. Use babs-check-setup to make sure it's good to go](https://pennlinc-babs.readthedocs.io/en/latest/walkthrough.html#id8)(https://pennlinc-babs.readthedocs.io/en/latest/walkthrough.html#step-2-2-use-babs-check-setup-to-make-sure-it-s-good-to-go)

when running
```
cd ~/babs_demo/my_BABS_project    # make sure you're in `my_BABS_project` folder

babs-check-setup \
    --project-root ${PWD} \
    --job-test
```
everything was okay until 
```
Submitting a test job, will take a while to finish...
Although the script will be submitted to the cluster to run, this job will not run the BIDS App; instead, this test job will gather setup information in the designated environment and will make sure jobs can finish successfully on current cluster.
sbatch: error: Batch job submission failed: Requested time limit is invalid (missing or exceeds some limit)
Traceback (most recent call last):
  File "/usr/people/yc3086/miniconda3/envs/babs/bin/babs-check-setup", line 8, in <module>
    sys.exit(babs_check_setup_main())
  File "/usr/people/yc3086/miniconda3/envs/babs/lib/python3.9/site-packages/babs/cli.py", line 296, in babs_check_setup_main
    babs_proj.babs_check_setup(input_ds, args.job_test)
  File "/usr/people/yc3086/miniconda3/envs/babs/lib/python3.9/site-packages/babs/babs.py", line 888, in babs_check_setup
    _, job_id_str, log_filename = submit_one_test_job(self.analysis_path, self.type_system)
  File "/usr/people/yc3086/miniconda3/envs/babs/lib/python3.9/site-packages/babs/utils.py", line 1466, in submit_one_test_job
    proc_cmd.check_returncode()
  File "/usr/people/yc3086/miniconda3/envs/babs/lib/python3.9/subprocess.py", line 460, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['sbatch', '--export=DSLOCKFILE=/mnt/bucket/scratch/yibeichen/babs_demo/my_BABS_project/analysis/.SLURM_datalad_lock', '--job-name', 'toy_test_job', '-e', '/mnt/bucket/scratch/yibeichen/babs_demo/my_BABS_project/analysis/logs/toy_test_job.e%A', '-o', '/mnt/bucket/scratch/yibeichen/babs_demo/my_BABS_project/analysis/logs/toy_test_job.o%A', '/mnt/bucket/scratch/yibeichen/babs_demo/my_BABS_project/analysis/code/check_setup/call_test_job.sh']' returned non-zero exit status 1.
```
@zhao-cy I'm happy to debug it if you can help point out which file I should look into. Is it something related to slurm script generation? In the generated slurm script, there is actually no time limit specified?

**Comment by zhao-cy** [comment]
There is no time limit specified by default. Could you please let me know the directives in the `analysis/code/participant_job.sh`, i.e., if you are in folder `my_BABS_project`, please try running `head analysis/code/participant_job.sh` - this should print out the first 10 lines of this file.

If a time limit must be specified for Princeton cluster, please add `hard_runtime_limit: xxx` within section `cluster_resources` in the YAML file. 20min is enough for this toy BIDS App. For the UMN MSI cluster I have access to, I would do `hard_runtime_limit: 20` to specify 20min, but please check out the manual for princeton cluster if that's the correct format to specify 20 min!

If this did not work, could you please confirm that the `sbatch` command generated by BABS (see the last line of the error message you provided) looks good to the Princeton cluster? 

If you still have some trouble, it will be great to send me your YAML file. Thanks for trying it out!

**Comment by yibeichan** [comment]
yes, adding `hard_runtime_limit: 00:20:00` works! so the time format is `HH:MM:SS`. Do you want me to add it to the doc?

**Comment by yibeichan** [comment]
however, the actual slurm jobs failed
```
Job status:
There are in total of 6 jobs to complete.
6 job(s) have been submitted; 0 job(s) haven't been submitted.
Among submitted jobs,
0 job(s) are successfully finished;
0 job(s) are pending;
0 job(s) are running;
6 job(s) are failed.
```

Most log files said
```
+ dssource=ria+file:///jukebox/scratch/yibeichen/babs_demo/my_BABS_project/input_ria#6ec708f4-504c-46a4-b9d8-e675c3274049
+ pushgitremote=/jukebox/scratch/yibeichen/babs_demo/my_BABS_project/output_ria/6ec/708f4-504c-46a4-b9d8-e675c3274049
+ subid=sub-01
+ sesid=ses-A
+ cd /jukebox/scratch/yibeichen/babs_demo/outputs
+ BRANCH=job-32148320-sub-01-ses-A
+ mkdir job-32148320-sub-01-ses-A
+ cd job-32148320-sub-01-ses-A
+ datalad clone ria+file:///jukebox/scratch/yibeichen/babs_demo/my_BABS_project/input_ria#6ec708f4-504c-46a4-b9d8-e675c3274049 ds
[INFO] Attempting a clone into /jukebox/scratch/yibeichen/babs_demo/outputs/job-32148320-sub-01-ses-A/ds 
[INFO] Attempting to clone from file:///jukebox/scratch/yibeichen/babs_demo/my_BABS_project/input_ria/6ec/708f4-504c-46a4-b9d8-e675c3274049 to /jukebox/scratch/yibeichen/babs_demo/outputs/job-32148320-sub-01-ses-A/ds 
[INFO] Completed clone attempts for Dataset(/jukebox/scratch/yibeichen/babs_demo/outputs/job-32148320-sub-01-ses-A/ds) 
+ cd ds
+ git remote add outputstore /jukebox/scratch/yibeichen/babs_demo/my_BABS_project/output_ria/6ec/708f4-504c-46a4-b9d8-e675c3274049
+ git checkout -b job-32148320-sub-01-ses-A
Switched to a new branch 'job-32148320-sub-01-ses-A'
+ datalad get -n inputs/data/BIDS/sub-01
[INFO] Attempting a clone into /jukebox/scratch/yibeichen/babs_demo/outputs/job-32148320-sub-01-ses-A/ds/inputs/data/BIDS 
[INFO] Attempting to clone from file:///jukebox/scratch/yibeichen/babs_demo/my_BABS_project/input_ria/4ce/418c5-a372-4b96-9935-5f60e2ece309 to /jukebox/scratch/yibeichen/babs_demo/outputs/job-32148320-sub-01-ses-A/ds/inputs/data/BIDS 
[INFO] Attempting to clone from osf://w2nu3 to /jukebox/scratch/yibeichen/babs_demo/outputs/job-32148320-sub-01-ses-A/ds/inputs/data/BIDS 
[WARNING] You appear to have cloned an empty repository. 
[INFO] Completed clone attempts for Dataset(/jukebox/scratch/yibeichen/babs_demo/outputs/job-32148320-sub-01-ses-A/ds/inputs/data/BIDS) 
[WARNING] Cloned /jukebox/scratch/yibeichen/babs_demo/outputs/job-32148320-sub-01-ses-A/ds/inputs/data/BIDS but could not find a branch with commits 
```

log `toy_sub-02_ses-D.o32148325` says
```
I'm in /mnt/bucket/scratch/yibeichen/babs_demo/my_BABS_project/analysis using /usr/people/yc3086/miniconda3/envs/babs/bin/python
install(ok): /jukebox/scratch/yibeichen/babs_demo/outputs/job-32148325-sub-02-ses-D/ds (dataset)
install(error): /jukebox/scratch/yibeichen/babs_demo/outputs/job-32148325-sub-02-ses-D/ds/inputs/data/BIDS (dataset) [Unknown commit identifier: master] [Unknown commit identifier: master]
get(impossible): inputs/data/BIDS/sub-02 [path does not exist]
action summary:
  get (impossible: 1)
  install (error: 1)
```

**Comment by zhao-cy** [comment]
Hi Yibei! I know you probably changed the YAML file where you added `hard_runtime_limit: 00:20:00`. After you did so, did you run `babs-init` and generate a new BABS project? i.e., are you currently using a new BABS project w/ updated configurations, or are you still using the original BABS project? It's better to do in the former way. 

If you've already working in the former way, could you please try cloning the input BIDS dataset to another directory (outside BABS project)? e.g., `datalad clone https://osf.io/w2nu3/ raw_BIDS_multi-ses`. I hope to make sure there is nothing wrong in the input dataset cloning part (e.g., OSF has some temporary issues).

Happy to schedule a quick zoom meeting to debug.

**Comment by zhao-cy** [comment]
Notes after our zoom meeting today:
- confirmed that all 5 dependent packages have very new versions, including `datalad-osf`
- confirmed that we can run thru on interactive node, but not on compute node..
- tried: removing `module purge` in `participant_job.sh`, but still got error as above on compute node
- tried: adding `source ~/.bashrc` in `participant_job.sh`, but still got error as above on compute node

**Comment by djarecka** [comment]
@yibeichan - btw. do you already have an mit address? perhaps you can ask for the openmind (mit cluster) account. I was testing there

**Comment by zhao-cy** [comment]
Hi @yibeichan ! Yes! Dorota has replicated the example walkthrough on MIT openmind cluster, so that's guaranteed to work. 

For Princeton cluster, I talked to Matt this morning, and it seems it's probably some configuration differences between compute nodes and interactive nodes that we are not aware of. So please ask the admin there. In addition, please try using dataset from openneuro, e.g., replace the http link of OSF dataset w/ `https://github.com/OpenNeuroDatasets/ds000102.git`. This is to rule out OSF issues.

**Comment by yibeichan** [comment]
hi @zhao-cy, do you have an equivalent version of this osf f=dataset on openneuro? `https://github.com/OpenNeuroDatasets/ds000102.git` doesn't have `ses-` so `babs-init` can't run successfully.

@djarecka yes, I got my openmind account last night. now chenying and I want to test the example on as many different clusters as possible.

**Comment by zhao-cy** [comment]
Hi @yibeichan! No we don't have shared our test data on openneuro. However for that openneuro dataset `ds000102`, you can specify `--type_session single-ses` when you run `babs-init`, as it's a single-session dataset. That dataset should work on MIT openmind cluster - I remeber @djarecka has tested it with babs.

I think for you to get started and get familiar with BABS, feel free to just use MIT cluster and proceed! It's def wonderful to know why princeton cluster failed, however,  i think it makes more sense to use MIT cluster for now!

**Comment by yibeichan** [comment]
Hi @zhao-cy, I tried many times with this open neuro dataset, got different errors, though (this time error is from git). 
then I asked my colleague @hvgazula, who told me there is no internet on the compute node at Princeton. I think in such instances, we should probably rewrite the workflow to clone first and then submit the jobs on the cluster.

**Comment by zhao-cy** [comment]
Hi @yibeichan ! Ah glad you know the answer! It also makes sense that for open neuro, you would have error from git.

Yes you're right - please clone the dataset to local disk space + get all the data content first, to make sure the job doesn't need internet access anymore (i.e., no need to fetch the data content from the OSF). Specifically, please follow the steps before [`step 1` in the example walkthrough](https://pennlinc-babs.readthedocs.io/en/latest/walkthrough.html#step-1-get-prepared); however, do not run commands in the last box, i.e., `datalad drop` and `datalad remove`. Instead, run `datalad get *` (i.e., get all data content) in the cloned dataset. When you run `babs-init`, please provide where the cloned input dataset `raw_BIDS_multi-ses` locates (full path) as the input data path: `--input BIDS /path/to/raw_BIDS_multi-ses`. Let me know if still does not work.

If you want to try out openneuro (though not necessary at the moment), please make sure you do similar things before you run `babs-init`.
