### ISSUE TITLE
[FIX] resubmitting jobs that are in queue: use `scancel` to delete the job in queue on Slurm clusters

### ISSUE THREAD

**Issue by zhao-cy** [PennLINC/babs#133]
Currently, BABS always uses `qdel` to delete the job, and `qdel` is an SGE command. Depending on the cluster system, for Slurm clusters, it should be `scancel`. Otherwise, it would cause error when `babs-status --resubmit(-job)` a pending job.

**Comment by zhao-cy** [comment]
Hi @djarecka @yibeichan ! On MIT or Princeton Slurm cluster, when you hope to cancel a job, would this command work? `scancel <job_id>`? 

I know it works on UMN MSI Slurm cluster, just hope to confirm that it also applies to other Slurm clusters.

Thanks,
Chenying

**Comment by yibeichan** [comment]
hi, so on princeton slurm `scancel <job_id>` it works. after `scancel`, `babs-status` will show that this job failed. I'll test it on openmind cluster soon.

**Comment by yibeichan** [comment]
hi, `scancel <job_id>` works on openmind cluster too! all good

**Comment by zhao-cy** [comment]
Perfect, thank you so much!
