### ISSUE TITLE
Deprecation warning from pandas during `babs-status`

### ISSUE THREAD

**Issue by asmacdo** [PennLINC/babs#168]
## Summary
`babs-status` returns the following output:

```
Did not request resubmit based on job states (no `--resubmit`).
/home/austin/devel/babs/babs/babs.py:1183: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'SUCCESS' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_job_updated.at[i_job, "last_line_stdout_file"] = \
/home/austin/devel/babs/babs/babs.py:1207: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'False' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_job_updated.at[i_job, "is_failed"] = False

Job status:
There are in total of 532 jobs to complete.
1 job(s) have been submitted; 531 job(s) haven't been submitted.
Among submitted jobs,
1 job(s) are successfully finished;
0 job(s) are pending;
0 job(s) are running;
0 job(s) are failed.
```

## Additional details

- BABS version: `main` branch`
- pandas version: `2.1.4`

**Comment by zhao-cy** [comment]
Thanks a lot Austin for marking this down! More details can be found in this issue: #140. If we want to make BABS compatible with latest version of `pandas`, it will require dramatic changes in `babs-status` and `babs-submit`. Therefore Matt recommends setting an upper boundary of `pandas` version to avoid this warning. I did not change it yet before I left - feel free to do so!

**Comment by yarikoptic** [comment]
1c: that would virtually mean that eventually babs would become incompatible with other things, like supported python versions etc since pandas would keep moving on, while babs would not be able to.  I would strongly recommend to make it compatible with more recent pandas.

**Comment by asmacdo** [comment]
@zhao-cy oops! I swear I looked through the issues, temporary blindness :)

I'll close this one.
