### ISSUE TITLE
[slurm] make `babs-init` compatible to slurm

### ISSUE THREAD

**Issue by zhao-cy** [PennLINC/babs#29]

**Comment by zhao-cy** [comment]
Hi @djarecka! I just wanted to leave a note to explain the strategy of `babs-init` for handling rerun. In the current main branch, the `babs-init` was implemented so that it can be rerun upon existing BABS project. However after seeing Austin's suggestion (#25) and talking to Matt, I realized that's not a good idea - which brings up risks fo overwriting existing BABS project.

Therefore I've changed the strategy in PR #19 (not ready to merge to main yet), so that `babs-init` cannot rerun on existing BABS project folder; and if it fails, it will cleans itself up.

I don't think this needs actions on your end, but please ignore the existing `if/else` checks of existence (e.g., if input datasets have been cloned, etc) in `babs-init` in current *main* branch - these checks will be removed when my PR #19 gets merged to main.

Thanks,
Chenying

**Comment by djarecka** [comment]
Thanks for explaining. I can see that there are many changes in your PR, and I'm thinking that it might be better if I switch to your branch to explore. Do you have any timeline when do you want to merge the PR?

**Comment by zhao-cy** [comment]
Hi @djarecka! I originally planned to merge it to main probably towards end of next week after I finish adding all pytests. However I can also merge it sooner (e.g., early next week) so that you can start from there / we won't work on the same branch at the same time. I can add more stuff I wanted to do in a new branch.

Let me know what you think?

Thanks,
Chenying

**Comment by zhao-cy** [comment]
Or, you may create a new branch from my current branch / PR #19 . In this way you can start now and don't need to wait for me. I just checked that although there will be merging conflicts in my PR, those involved files are not critical so should not be a big deal. Let me know what you think?

Thanks,
Chenying

**Comment by zhao-cy** [comment]
But in either way, please wait for me for another push today so that I make sure circle ci won't fail before you create a new branch. Will post here as soon as circle ci passes!

**Comment by djarecka** [comment]
ok, today, I'm mostly playing with it.

I think once you are done with some specific changes you had in mind, you can merge the PR and add the tests in a new PR, but I don't want to interfere with your plans. I can start a new branch from yours.

**Comment by zhao-cy** [comment]
Hi Dorota! The bugs have been fixed so feel free to create a branch from my current PR #19. I plan to merge my PR into main on Monday and I'll let you know once that's done.

Thanks,
Chenying

**Comment by djarecka** [comment]
ok, thanks for your update!

**Comment by zhao-cy** [comment]
This has been done by release 0.0.4.
